name: Pandoc

on: push
    # tags-ignore:
    #   - 'not-release'

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Create docs directory
      #   run: mkdir -p docs/

      # - name: Create pdf
      #   id: create-pdf
      #   uses: docker://sintoris/texlive:routes
      #   with:
      #     args: >-
      #       --defaults=conf/pdf.yaml
      #       -N -f markdown-implicit_figures
      
      - name: Create docs directory
        run: mkdir -p docs/html
            
      - name: Create html
        id: create-html
        uses: docker://sintoris/texlive:routes
        with:
          args: >-
            --defaults=conf/html.yaml
            -N -f markdown-implicit_figures
      
      - name: Push to GitHub
        run: |
          mv *.svg docs/html
          rm *.src.html
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -f docs/html/*
          git commit -m "Add generated HTML page"
          git push

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html




